# Generated by Skyramp v1.3.29 on 2026-06-25 23:42:25.527319304 +0000 UTC m=+430.361265122
# Command: skyramp generate contract rest http://localhost/api/v2/measurement-category/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output measurement_category_get_contract_test.py \
# 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger \
# 		--overwrite \
# 		--provider \
# 		--response-data {"count":1,"next":null,"previous":null,"results":[{"id":"c0000000-0000-0000-0000-000000000001","name":"TestCategory","unit":"cm","entry_count":5}]} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/measurement-category/ GET
def test_measurement_category_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_measurement_category_GET_response_body = r'''{
        "count": 1,
        "next": null,
        "previous": null,
        "results": [
            {
                "entry_count": 5,
                "id": "c0000000-0000-0000-0000-000000000001",
                "name": "TestCategory",
                "unit": "cm"
            }
        ]
    }'''

    # Execute Request
    measurement_category_GET_response = client.send_request(
        url=URL,
        path="/api/v2/measurement-category/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert measurement_category_GET_response.status_code == 200
    assert skyramp.check_schema(measurement_category_GET_response, expected_measurement_category_GET_response_body)
    assert skyramp.get_response_value(measurement_category_GET_response, "count") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "next") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "previous") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "results") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "results.0.entry_count") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "results.0.id") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "results.0.name") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "results.0.unit") is not None


if __name__ == "__main__":
    test_measurement_category_get()
