# Generated by Skyramp v1.3.29 on 2026-06-25 23:42:28.99513244 +0000 UTC m=+433.829078269
# Command: skyramp generate contract rest http://localhost/api/v2/measurement-category/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output measurement_category_post_contract_test.py \
# 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"NewCategory-2026","unit":"kg"} \
# 		--response-data {"id":"c0000000-0000-0000-0000-000000000002","name":"NewCategory-2026","unit":"kg","entry_count":0} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/measurement-category/ POST
def test_measurement_category_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    measurement_category_POST_request_body = r'''{
        "name": "NewCategory-2026",
        "unit": "kg"
    }'''

    # Expected Response Body
    expected_measurement_category_POST_response_body = r'''{
        "entry_count": 0,
        "id": "c0000000-0000-0000-0000-000000000002",
        "name": "NewCategory-2026",
        "unit": "kg"
    }'''

    # Execute Request
    measurement_category_POST_response = client.send_request(
        url=URL,
        path="/api/v2/measurement-category/",
        method="POST",
        body=measurement_category_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert measurement_category_POST_response.status_code == 201
    assert skyramp.check_schema(measurement_category_POST_response, expected_measurement_category_POST_response_body)
    assert skyramp.get_response_value(measurement_category_POST_response, "entry_count") == 0
    assert skyramp.get_response_value(measurement_category_POST_response, "id") is not None
    assert skyramp.get_response_value(measurement_category_POST_response, "name") == "NewCategory-2026"
    assert skyramp.get_response_value(measurement_category_POST_response, "unit") == "kg"


if __name__ == "__main__":
    test_measurement_category_post()
