# Generated by Skyramp v1.3.29 on 2026-06-25 23:42:38.063550963 +0000 UTC m=+442.897496781
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output measurement_category_entry_count_integration_test.py \
# 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger/scenario_measurement_category_entry_count.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "EntryCountTest-2026",
        "unit": "cm"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement-category/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "EntryCountTest-2026"
    assert skyramp.get_response_value(endpoint_1_POST_response, "unit") == "cm"
    assert skyramp.get_response_value(endpoint_1_POST_response, "entry_count") == 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    # Chain category ID from step 1 response
    category_id = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    endpoint_3_POST_request_body = '{{"category": "{}", "date": "2026-06-25", "notes": "test entry", "value": 42.5}}'.format(category_id)

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "date") == "2026-06-25"
    assert skyramp.get_response_value(endpoint_3_POST_response, "value") == 42.5
    assert skyramp.get_response_value(endpoint_3_POST_response, "notes") == "test entry"

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement-category/{measurement-category}/",
        method="GET",
        headers=headers,
        path_params={"measurement-category": category_id}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "entry_count") == 1
    assert skyramp.get_response_value(endpoint_2_GET_response, "name") == "EntryCountTest-2026"
    assert skyramp.get_response_value(endpoint_2_GET_response, "unit") == "cm"
    assert skyramp.get_response_value(endpoint_2_GET_response, "id") == category_id


if __name__ == "__main__":
    test_integration()
