# Generated by Skyramp v1.3.29 on 2026-06-25 23:38:23.991290661 +0000 UTC m=+188.804472838
# Command: skyramp generate contract rest http://localhost/api/v2/weightentry/ \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output weightentry_year_filter_empty_contract_test.py \
# 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger \
# 		--overwrite \
# 		--provider \
# 		--query-params year=9999 \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/weightentry/ GET
def test_weightentry_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    weightentry_GET_response = client.send_request(
        url=URL,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers,
        query_params={"year": "9999"}
    )

    # Generated Assertions
    assert weightentry_GET_response.status_code == 200
    assert skyramp.get_response_value(weightentry_GET_response, "count") == 0
    assert skyramp.get_response_value(weightentry_GET_response, "results") is not None
    assert skyramp.get_response_value(weightentry_GET_response, "results.0") is None


if __name__ == "__main__":
    test_weightentry_get()
