# Generated by Skyramp v1.3.29 on 2026-06-25 23:38:18.920074356 +0000 UTC m=+183.733256543
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output weightentry_year_filter_isolation_integration_test.py \
# 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger/scenario_weightentry_year_filter_isolation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2024-06-15T10:00:00Z",
        "weight": "75.50"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "date") == "2024-06-15T10:00:00Z"
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "75.50"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "date": "2023-03-10T10:00:00Z",
        "weight": "80.25"
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "date") == "2023-03-10T10:00:00Z"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "weight") == "80.25"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") > 0

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers,
        query_params={"year": ["2024"]}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") >= 1
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.date") == "2024-06-15T10:00:00Z"
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.weight") == "75.50"


if __name__ == "__main__":
    test_integration()
