# Generated by Skyramp v1.3.30 on 2026-06-29 23:45:10.12862591 +0000 UTC m=+268.160668068
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output weightentry_no_year_filter_backward_compat_integration_test.py \
# 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/wger/scenario_weightentry-no-year-filter-backward-compat.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2024-06-15T10:00:00Z",
        "weight": "65.00"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "65.00"
    assert skyramp.get_response_value(endpoint_1_POST_response, "date") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "user") > 0

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") >= 1
    assert skyramp.get_response_value(endpoint_1_GET_response, "next") is None
    assert skyramp.get_response_value(endpoint_1_GET_response, "previous") is None
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") > 0


if __name__ == "__main__":
    test_integration()
