// Generated by Skyramp v1.3.29 on 2026-06-26 00:03:44.854850009 +0000 UTC m=+551.430526430
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output measurement_category_entry_count_ui.spec.ts \
// 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/wger-fullstack/wger-fullstack/.skyramp/measurement_category_entry_count_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(630000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto("http://localhost/en/user/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("#id_login").fill("admin");
    await page.locator("#id_password").fill("adminadmin");
    await page.getByRole("button", { name: "Login" }).click();

    await expect(page).toHaveURL(/\/en\/dashboard/);

    await page.goto("http://localhost/en/measurement/");
    await page.waitForLoadState('networkidle');

    await expect(page).toHaveURL(/\/en\/measurement/);
    await expect(page.getByRole('link', { name: 'Measurements' })).toBeVisible();

    expect(errors).toHaveLength(0);
});
