# Generated by Skyramp v1.3.29 on 2026-06-26 00:03:49.479545444 +0000 UTC m=+556.055221866
# Command: skyramp generate contract rest http://localhost/api/v2/measurement-category/ \
# 		--api-schema http://localhost/api/v2/schema?format=json \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output measurement_category_entry_count_contract_test.py \
# 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /api/v2/measurement-category/ GET
def test_measurement_category_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_measurement_category_GET_response_body = r'''{
        "count": 123,
        "results": [
            {
                "entry_count": 5,
                "name": "Biceps",
                "unit": "cm"
            }
        ]
    }'''

    # Execute Request
    measurement_category_GET_response = client.send_request(
        url=URL,
        path="/api/v2/measurement-category/",
        method="GET",
        headers=headers,
        query_params={
            "id": None,
            "limit": None,
            "name": None,
            "offset": None,
            "ordering": None,
            "unit": None
        }
    )

    # Generated Assertions
    assert measurement_category_GET_response.status_code == 200
    assert skyramp.check_schema(measurement_category_GET_response, expected_measurement_category_GET_response_body)
    assert skyramp.get_response_value(measurement_category_GET_response, "count") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "count") >= 0
    assert skyramp.get_response_value(measurement_category_GET_response, "results.0.entry_count") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "results.0.entry_count") >= 0
    assert isinstance(skyramp.get_response_value(measurement_category_GET_response, "results.0.entry_count"), int)
    assert skyramp.get_response_value(measurement_category_GET_response, "results.0.name") is not None
    assert skyramp.get_response_value(measurement_category_GET_response, "results.0.unit") is not None


if __name__ == "__main__":
    test_measurement_category_get()
