# Generated by Skyramp v1.3.29 on 2026-06-26 00:04:06.88982168 +0000 UTC m=+573.465498101
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output measurement_category_entry_count_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger-fullstack/wger-fullstack/tests/skyramp/scenario_measurement_category_entry_count_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "Chest",
        "unit": "cm"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement-category/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "Chest"
    assert skyramp.get_response_value(endpoint_1_POST_response, "unit") == "cm"
    assert skyramp.get_response_value(endpoint_1_POST_response, "entry_count") == 0
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    # Chain category ID from POST response
    measurement_category = str(skyramp.get_response_value(endpoint_1_POST_response, "id"))
    category_id = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body (use chained category_id)
    endpoint_3_POST_request_body = '{{"category": "{}","date": "2026-01-15","notes": "","value": 95.5}}'.format(category_id)

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement/",
        method="POST",
        body=endpoint_3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "value") == 95.5
    assert skyramp.get_response_value(endpoint_3_POST_response, "date") == "2026-01-15"
    assert skyramp.get_response_value(endpoint_3_POST_response, "notes") == ""
    assert skyramp.get_response_value(endpoint_3_POST_response, "category") is not None

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/measurement-category/{measurement-category}/",
        method="GET",
        headers=headers,
        path_params={"measurement-category": measurement_category}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "entry_count") == 1
    assert skyramp.get_response_value(endpoint_2_GET_response, "name") == "Chest"
    assert skyramp.get_response_value(endpoint_2_GET_response, "unit") == "cm"
    assert skyramp.get_response_value(endpoint_2_GET_response, "id") is not None


if __name__ == "__main__":
    test_integration()
